name: Linter

on: 
  push:
    branches: 
      master

jobs:
  lint: 
    name: Lint code base
    runs-on: ubuntu-latest

    steps: 
      name: Git clone my repository
      uses: actions/checkout@v1

      name: make lint
      run : make lint